# _config.yml for mystic-devloper.github.io

#--------------------------------------------------
# Basic Site Info
#--------------------------------------------------
title: "Mystic-Devloper"
description: "Personal site of Suryansh Singh – Research, Games, Code, and more."
baseurl: ""
url: "https://mystic-devloper.github.io"
author: "Suryansh Singh"
manifest: "/assets/manifest.json"
browserconfig: "assets/browserconfig.xml"
favicon: "/assets/favicons/favicon512x512.png"
logo: "/assets/logo/site-logo.svg"
main_style: "/assets/styles.scss"

#--------------------------------------------------
# Build Settings
#--------------------------------------------------
theme: null # Left blank (using custom styles)
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num"

#--------------------------------------------------
# Language and Encoding
#--------------------------------------------------
encoding: "utf-8"
lang: "en-US"

#--------------------------------------------------
# Google Analytics (for website views analytics)
#--------------------------------------------------
google_analytics: "G-5JSHJ036S2"
google_analytics_anonymize_ip: true

#--------------------------------------------------
# Assets Paths
#--------------------------------------------------
favicon_path: "/assets/favicons"
image_path: "/assets/images"
js_path: "/assets/js"

#--------------------------------------------------
# Assets
#--------------------------------------------------
favicons:
  ico: "/assets/favicons/favicon.ico"
  main_apple_touch: "/assets/favicons/apple-touch-icon.png"
  svg: "/assets/favicons/favicon.svg"
  16:  "/assets/favicons/favicon16x16.png"
  32:  "/assets/favicons/favicon32x32.png"
  48:  "/assets/favicons/favicon48x48.png"
  64:  "/assets/favicons/favicon64x64.png"
  128: "/assets/favicons/favicon128x128.png"
  144: "/assets/favicons/favicon144x144.png"
  180: "/assets/favicons/favicon180x180.png"
  192: "/assets/favicons/favicon192x192.png"
  256: "/assets/favicons/favicon256x256.png"
  324: "/assets/favicons/favicon324x324.png"
  512: "/assets/favicons/favicon512x512.png"
  1024: "/assets/favicons/favicon1024x1024.png"

splash_screens:
  - device: iphone-original
    orientation: portrait
    width: 320
    height: 480
    ratio: 1
    image: "/assets/favicons/splash-ios-iphone-portrait.png"

  - device: iphone-original
    orientation: landscape
    width: 480
    height: 320
    ratio: 1
    image: "/assets/favicons/splash-ios-iphone-landscape.png"

  - device: iphone-retina
    orientation: portrait
    width: 640
    height: 1136
    image: "/assets/favicons/splash-ios-iphone-portrait.png"

  - device: iphone-retina
    orientation: landscape
    width: 1136
    height: 640
    image: "/assets/favicons/splash-ios-iphone-landscape.png"

  - device: iphone-plus
    orientation: portrait
    width: 1242
    height: 2208
    image: "/assets/favicons/splash-ios-iphoneplus-portrait.png"

  - device: iphone-plus
    orientation: landscape
    width: 2208
    height: 1242
    image: "/assets/favicons/splash-ios-iphoneplus-landscape.png"

  - device: iphonex
    orientation: portrait
    width: 1125
    height: 2436
    image: "/assets/favicons/splash-ios-iphonex-portrait.png"

  - device: iphonex
    orientation: landscape
    width: 2436
    height: 1125
    image: "/assets/favicons/splash-ios-iphonex-landscape.png"

  - device: ipad
    orientation: portrait
    width: 768
    height: 1024
    image: "/assets/favicons/splash-ios-ipad-portrait.png"

  - device: ipad
    orientation: landscape
    width: 1024
    height: 768
    image: "/assets/favicons/splash-ios-ipad-landscape.png"

  - device: ipadpro
    orientation: portrait
    width: 2048
    height: 2732
    image: "/assets/favicons/splash-ios-ipadpro-portrait.png"

  - device: ipadpro
    orientation: landscape
    width: 2732
    height: 2048
    image: "/assets/favicons/splash-ios-ipadpro-landscape.png"

# Android handles splash screens automatically through manifest.json

#--------------------------------------------------
# Navigation
#--------------------------------------------------
navigation:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog/"
  - title: "Research"
    url: "/research/"
  - title: "Projects"
    url: "/projects/"
  - title: "Games"
    url: "/games/"
  - title: "About"
    url: "/about/"
  - title: "Search"
    url: "/search/"

#--------------------------------------------------
# Styling Settings
#--------------------------------------------------
sass:
  sass_dir: _sass
  style: compressed

#--------------------------------------------------
# Exclusions from build
#--------------------------------------------------
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md

#--------------------------------------------------
# Defaults
#--------------------------------------------------
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Suryansh Singh"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

#--------------------------------------------------
# Social links
#--------------------------------------------------
social_links:
    - "https://github.com/mystic-devloper"
    - "https://researchbysurya.substack.com"
    - "https://gamesandnumbers.substack.com"
    - "https://x.com/sinister_surya"
    - "https://www.linkedin.com/in/research-by-surya"

#--------------------------------------------------
# SEO
#--------------------------------------------------
seo:
  name: "Suryansh Singh"
  type: "Person"
  image: "/favicons-512x512.png"
  twitter: "sinister_surya"

#--------------------------------------------------
# Sitemap
#--------------------------------------------------
sitemap:
  exclude:
    - "/404.html"
